# Generated by Django 6.0 on 2026-01-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0002_remove_device_description_remove_device_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'جهاز', 'verbose_name_plural': 'الأجهزة'},
        ),
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الجهاز'),
        ),
        migrations.AddField(
            model_name='device',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='devices/', verbose_name='صورة الجهاز'),
        ),
        migrations.AddField(
            model_name='device',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=3, verbose_name='التقييم'),
        ),
        migrations.AddField(
            model_name='device',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='التخصص/العيادة'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=100, verbose_name='اسم الجهاز'),
        ),
    ]
