# Generated by Django 6.0 on 2026-01-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0003_alter_device_options_device_description_device_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
    ]
