# Generated by Django 6.0 on 2026-01-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0004_alter_device_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='تاريخ العطلة')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='السبب')),
            ],
            options={
                'verbose_name': 'يوم عطلة',
                'verbose_name_plural': 'أيام العطل',
            },
        ),
    ]
