# Generated by Django 6.0 on 2026-01-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radiology', '0005_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='التقييم'),
        ),
        migrations.AlterField(
            model_name='device',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='التخصص'),
        ),
    ]
